// <auto-generated />
namespace meditatii.web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class newupdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newupdate));
        
        string IMigrationMetadata.Id
        {
            get { return "202004240526262_newupdate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
