// <auto-generated />
namespace Meditatii.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addrolestousers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addrolestousers));
        
        string IMigrationMetadata.Id
        {
            get { return "201810291509355_addrolestousers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
